title: keramitas
description: >-
  AI and stuff
author:
  name: Romain Keramitas
  email: "r.keramitas@gmail.com"
url: "http://keramitas.io"
baseurl: ""

theme: minima

header_pages:
  - about.md
  - contact.md

exclude:
  - README.md
  - LICENSE

show_excerpts: true

plugins:
  - jekyll-analytics
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll_analytics:
  Plausible:
    domain: "keramitas.io"
    source: "https://plausible.io/js/plausible.js"
